name: store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pics/
    - assets/brands/
    - .env

  fonts:
    - family: URW Geometric Med
      fonts:
        - asset: assets/fonts/URWGeometricMedium.otf
    - family: URW Geometric SemBd
      fonts:
        - asset: assets/fonts/URWGeometricSemiBold.otf
    - family: URW Geometric
      fonts:
        - asset: assets/fonts/URWGeometricBold.otf
